### user routes work well
GET http://localhost:8060/alluser
### verify work well
GET http://localhost:8060/authentication
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMDkzMzgsImV4cCI6MTU3OTAxMjkzOH0.kNLdNlfXOV5qGr6J7XOyLRxfrcGX9vvcMdzORkTpSqM
Content-Type: application/json

{
    "id_research_team":7
}
### work welll
POST http://localhost:8060/authentication
Content-Type: application/json 

{
    "nameuniversity":"ensias",
    "research_team":"1",
    "name_team":"ensiasteam",
    "full_name_research_team" : "hatim",
    "password_hashed_research_team" : "00000",
    "email_research_team" : "test@hotmail.fr",
    "phone_number_research_team" : "09458453"
}
### work well
POST http://localhost:8060/authentication
Content-Type: application/json 

{
    "research_team" : "3",
    "full_name_agent" : "GU",
    "password_hashed_agent" : "jdsh",
    "email_agent" : "GU@hotmail.fr",
    "phone_number_agent" : "09458453"
}
### work well
PUT http://localhost:8060/authentication/7
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMDkzMzgsImV4cCI6MTU3OTAxMjkzOH0.kNLdNlfXOV5qGr6J7XOyLRxfrcGX9vvcMdzORkTpSqM
Content-Type: application/json 

{
    "password_hashed_research_team":"PasswordChanged"
}




###demande route
GET http://localhost:8060/demande/7
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMDkzMzgsImV4cCI6MTU3OTAxMjkzOH0.kNLdNlfXOV5qGr6J7XOyLRxfrcGX9vvcMdzORkTpSqM

# auth_token: get the token after the login 

### insert demande work well 
POST  http://localhost:8060/demande/7
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMTU0MDgsImV4cCI6MTU3OTAxOTAwOH0.rXcBArgFJzFwcPhN3kwY65LfzrvFPJZyYOc8UtzPOxg
Content-Type: application/json

{
    "name_demande":"second",
    "description":"this is the second demande"
}
### work well 
PUT  http://localhost:8060/demande/2
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMDkzMzgsImV4cCI6MTU3OTAxMjkzOH0.kNLdNlfXOV5qGr6J7XOyLRxfrcGX9vvcMdzORkTpSqM
Content-Type: application/json

{
    "type_idea":"first type",
    "state":"1",
    "name_competence_pool":"first_competences"
}
### work well
DELETE http://localhost:8060/demande/2
### work well
GET http://localhost:8060/alldemande
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMDkzMzgsImV4cCI6MTU3OTAxMjkzOH0.kNLdNlfXOV5qGr6J7XOyLRxfrcGX9vvcMdzORkTpSqM

###competences pool route
GET http://localhost:8060/competencepool
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMDkzMzgsImV4cCI6MTU3OTAxMjkzOH0.kNLdNlfXOV5qGr6J7XOyLRxfrcGX9vvcMdzORkTpSqM

###
POST http://localhost:8060/competencepool
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMDkzMzgsImV4cCI6MTU3OTAxMjkzOH0.kNLdNlfXOV5qGr6J7XOyLRxfrcGX9vvcMdzORkTpSqM
Content-Type: application/json

{
    "name_competences_pool":"info",
    "responsable_name":"hamgggid"
}

### login route
POST http://localhost:8060/login
Content-Type: application/json

{
    "email_user":"test@hotmail.fr",
    "password_hashed":"PasswordChanged",
    "type":"1"
}
### add auth_token
GET http://localhost:8060/startup/7
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMTQxMzgsImV4cCI6MTU3OTAxNzczOH0.FLGnnmHh3IU_SWYNCiNR8XV2ZCwSmYKexUCalHZ9WBg

### work well
POST http://localhost:8060/startup/7/9
auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9yZXNlYXJjaF90ZWFtIjo3LCJpYXQiOjE1NzkwMTUwMTIsImV4cCI6MTU3OTAxODYxMn0.3aiJAgN2JBrRj-k80xAYuGjfHeDcMumEqYKg6cxU-wE
Content-Type: application/json

{
    "name_startup":"first startup",
    "business_plan":"this is a dummy businness plan to test our project IVON UM5R"
}