### user routes work well
GET http://localhost:8060/alluser
### verify work well
GET http://localhost:8060/authentication
# auth_token: get the token after the login 
### work welll
POST http://localhost:8060/authentication
Content-Type: application/json 

{
    "nameuniversity":"ensias",
    "research_team":"1",
    "name_team":"ensiasteam",
    "full_name_research_team" : "hatim",
    "password_hashed_research_team" : "jay",
    "email_research_team" : "hathat@hotmail.fr",
    "phone_number_research_team" : "09458453"
}
### work well
POST http://localhost:8060/authentication
Content-Type: application/json 

{
    "research_team" : "3",
    "full_name_agent" : "GU",
    "password_hashed_agent" : "jdsh",
    "email_agent" : "hafthdfat@hotmail.fr",
    "phone_number_agent" : "09458453"
}
### work well
PUT http://localhost:8060/authentication/6
Content-Type: application/json 

{
    "password_hashed_research_team":"PasswordChanged"
}




###demande route
GET http://localhost:8060/demande
# auth_token: get the token after the login 

### need auth 
POST  http://localhost:8060/demande
# auth_token: get the token after the login 

Content-Type: application/json


{
    "name_demande":"first",
    "description":"this is the first demande",
}
### work well 
PUT  http://localhost:8060/demande/2
Content-Type: application/json

{
    "type_idea":"first type",
    "state":"1",
    "name_competence_pool":"first_competences"
}
### work well
DELETE http://localhost:8060/demande/2
### add auth token
GET http://localhost:8060/alldemande
###competences pool route
GET http://localhost:8060/competencepool
###
POST http://localhost:8060/competencepool
Content-Type: application/json

{
    "name_competences_pool":"info",
    "responsable_name":"hamgggid"
}

### login route
POST http://localhost:8060/login
Content-Type: application/json

{
    "email_user":"hathat@hotmail.fr",
    "password_hashed":"hatidsm",
    "type":"2"
}
### add auth_token
GET http://localhost:8060/startup
auth_token :

POST http://localhost:8060/startup/2/29
Content-Type: application/json

{
    "name_startup":"first startup",
    "business_plan":"this is a dummy businness plan to test our project IVON UM5R"
}